# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastspeech',
                'doc_host': 'https://ahadjawaid.github.io',
                'git_url': 'https://github.com/ahadjawaid/fastspeech',
                'lib_path': 'fastspeech'},
  'syms': {'fastspeech.core': {'fastspeech.core.foo': ('core.html#foo', 'fastspeech/core.py')}}}
